version: "3.9"
services:
  mqs-emqx:
    image: emqx:latest
    container_name: mqs-emqx
    restart: always
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    network_mode: host
    environment:
      - EMQX_LISTENERS__TCP__DEFAULT__BIND=1883
      - EMQX_HOST=0.0.0.0

  mqs-node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

volumes:
  mqs-activemq:
    driver: local