version: "3.9"
services:

  mqs-aedes:
    container_name: mqs-aedes
    image: moscajs/aedes:latest
    restart: always
    ports:
      - 1883:1883
    stop_signal: SIGINT
    command: --config /data/config.js # add here the options to pass to aedes
    volumes:
      - ./mqs-aedes/:/data # map the local folder to aedes
    cpuset: "0"
    networks:
      - mqs-net

networks:
  mqs-net: null