version: "3.9"
services:
  mqs-mosquitto:
    image: eclipse-mosquitto
    container_name: mqs-mosquitto
    restart: always
    volumes:
      - ./mqs-mosquitto/config:/mosquitto/config
      - ./mqs-mosquitto/data:/mosquitto/data:rw
      - ./mqs-mosquitto/log:/mosquitto/log:rw
    build:
      network: host
    network_mode: host

  mqs-node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

volumes:
  mqs-mosquitto-config:
  mqs-mosquitto-data:
  mqs-mosquitto-log: