version: "3.9"
services:
  mqs-activemq:
    image: woahbase/alpine-activemq:x86_64
    container_name: activemq-5.16.0
    restart: always
    network_mode: host
    volumes: 
      - /etc/localtime:/etc/localtime:ro

volumes:
  mqs-activemq:
    driver: local