version: "3.9"
services:
  mqs-activemq:
    image: woahbase/alpine-activemq:x86_64
    container_name: activemq-5.16.0
    restart: always
    network_mode: host
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      
  mqs-node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

volumes:
  mqs-activemq:
    driver: local