version: "3.9"
services:

  mqs-activemq:
    image: woahbase/alpine-activemq:x86_64
    container_name: activemq-5.16.0
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms/openwire
      - "61616:61616"
    volumes: 
      - /etc/localtime:/etc/localtime:ro

volumes:
  mqs-activemq:
    driver: local