version: "3.9"
services:

  mqs-aedes:
    container_name: mqs-aedes
    image: moscajs/aedes:latest
    restart: always
    ports:
      - 5883:5883
    stop_signal: SIGINT
    command: --config /data/config.js # add here the options to pass to aedes
    volumes:
      - ./mqs-aedes/:/data # map the local folder to aedes
    #depends_on:
    ##  - mongo
    networks:
      - mqs-net

  mqs-mosquitto:
    image: eclipse-mosquitto
    container_name: mqs-mosquitto
    ports:
      - "1883:1883" #default mqtt port
    volumes:
      - ./mqs-mosquitto/config:/mosquitto/config
      - ./mqs-mosquitto/data:/mosquitto/data:rw
      - ./mqs-mosquitto/log:/mosquitto/log:rw
    networks:
      - mqs-net

  mqs-influxdb:
    image: influxdb:2.7
    container_name: mqs-influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: superuser
      DOCKER_INFLUXDB_INIT_PASSWORD: Passw0rd!
      DOCKER_INFLUXDB_INIT_ORG: MyOrg
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: N3Z_uUDSQ61qVp93K5dNzH3rbNcKxtphDLrjfS_DcX2cdTr3nR2pOlixGCx6HQ8VI66nqnyztOlPFoWFXoe62Q==
      DOCKER_INFLUXDB_INIT_BUCKET: NBomber
    ports:
      - 8086:8086
    networks:
      - mqs-net
    volumes:
    - mqs-influxdb-data:/var/lib/influxdb2

  mqs-grafana:
    image: grafana/grafana-oss:9.5.3
    container_name: mqs-grafana
    ports:
      - 3000:3000
    networks:
      - mqs-net
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  mqs-node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Moscow
    ports:
      - "1880:1880"
    networks:
      - mqs-net
    volumes:
      - mqs-node-red-data:/data


volumes:
  mqs-node-red-data:
  mqs-mosquitto-config:
  mqs-mosquitto-data:
  mqs-mosquitto-log:
  mqs-influxdb-data:

networks:
  mqs-net: null